#!/usr/bin/env python3
"""Generate a runnable SDL3 Elisa application from an Elisa IDE project.

The project document remains the source of truth. Generated files are staged in
an adjacent temporary directory and published only after the previous ownership
manifest has been checked. Handler source is user-owned and is never written.
"""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import shutil
import sys
import tempfile

FORMAT = "elisa-ide-generation-manifest"
VERSION = 1
MAX_FILES = 512


def digest(data: bytes) -> str:
    """Return the fixed-width FNV-1a digest used by GenerationManifest."""
    value = 14695981039346656037
    for byte in data:
        value ^= byte
        value = (value * 1099511628211) & 0xFFFFFFFFFFFFFFFF
    return f"{value:016x}"


def normalized_relative(path: pathlib.Path) -> str:
    value = path.as_posix()
    if value.startswith("/") or value in ("", ".") or ".." in path.parts:
        raise ValueError(f"unsafe generated relative path: {value}")
    return value


def read_json(path: pathlib.Path) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read project JSON {path}: {exc}") from exc
    if not isinstance(value, dict) or value.get("format") != "elisa-ide-project":
        raise ValueError("project is not an elisa-ide-project document")
    return value


def shell_quote(path: pathlib.Path) -> str:
    return str(path)


def run_cli_validate(cli: pathlib.Path, project: pathlib.Path) -> None:
    import subprocess
    result = subprocess.run([str(cli), "validate", str(project)], text=True, capture_output=True)
    if result.returncode != 0:
        output = (result.stdout + result.stderr).strip()
        raise ValueError(f"project validation failed:\n{output}")


def run_cli_generate(cli: pathlib.Path, form: pathlib.Path, output: pathlib.Path, source_map: pathlib.Path) -> tuple[bytes, bytes]:
    import subprocess
    result = subprocess.run([str(cli), "generate", str(form), str(output), str(source_map)], text=True, capture_output=True)
    if result.returncode != 0:
        output_text = (result.stdout + result.stderr).strip()
        raise ValueError(f"form generation failed for {form}:\n{output_text}")
    return output.read_bytes(), source_map.read_bytes()


def module_name(source: bytes) -> str:
    match = re.search(rb"^module ([A-Za-z_][A-Za-z0-9_]*):", source, re.MULTILINE)
    if not match:
        raise ValueError("generated view has no valid module declaration")
    return match.group(1).decode("ascii")


def source_literal(value: str) -> str:
    # The generated app contains Elisa string literals. Keep Unicode bytes and
    # escape only syntax/control characters.
    result = ['"']
    for char in value:
        code = ord(char)
        if char == '"':
            result.append('\\"')
        elif char == "\\":
            result.append("\\\\")
        elif char == "\n":
            result.append("\\n")
        elif char == "\r":
            result.append("\\r")
        elif char == "\t":
            result.append("\\t")
        elif code < 32 or code == 127:
            result.append(f"\\u00{code:02x}")
        else:
            result.append(char)
    result.append('"')
    return "".join(result)


def app_source(framework_include: str, view_include: str, handlers_include: str | None,
               view_module: str, title: str, width: int, height: int, max_frames: int) -> bytes:
    clear = "UiCore::Color{r: 20, g: 22, b: 28, a: 255}"
    handlers_line = f"include {source_literal(handlers_include)}\n" if handlers_include else ""
    source = f'''# Generated by Elisa IDE. Do not edit; regenerate from the project and form documents.
include {source_literal(framework_include)}
include {source_literal(view_include)}
{handlers_line}
# This file owns the framework application callbacks.
global mutable _elisa_designer_view_ready: bool = false

def app_init() -> void:
    _elisa_designer_view_ready <- {view_module}::build()

def app_widget_event(widget: usize, event: i32) -> void:
    return if not _elisa_designer_view_ready
    {view_module}::dispatch_widget_event(widget, event)

def app_event(event: UiCore::Event) -> void:
    UiHandles::handle(event) if _elisa_designer_view_ready

def app_text_input(text: sview) -> void:
    UiHandles::insert_text(text) if _elisa_designer_view_ready

def app_text_editing(text: sview, selected_start: i32, selected_length: i32) -> void:
    UiHandles::update_marked_text_utf8_characters(text, selected_start, selected_length) if _elisa_designer_view_ready

def app_frame() -> void:
    UiCore::clear({clear})
    return if not _elisa_designer_view_ready
    UiHandles::layout(UiCore::viewport_width(), UiCore::viewport_height())
    UiHandles::paint()

def main() -> i64:
    return UiSdl3::run({source_literal(title)}, {width}, {height}, {max_frames})
'''
    return source.encode("utf-8")


def project_readme(project: dict, project_path: pathlib.Path, namespace: str,
                   app_name: str, handler_path: pathlib.Path | None,
                   output_root: pathlib.Path) -> bytes:
    """Emit the reproducible handoff document for a generated project.

    This file is deliberately generated alongside the source and ownership
    manifest. It gives a project recipient enough information to regenerate,
    build, and run the app without having to infer which files are safe to
    edit. Paths in the document are relative or placeholders so output bytes
    remain deterministic across machines.
    """
    project_name = str(project.get("name") or namespace)
    manifest_name = project_path.name
    output_name = output_root.name
    handler_display = (
        os.path.relpath(handler_path, project_path.parent).replace(os.sep, "/")
        if handler_path is not None else
        "(none; Elisa IDE emitted a placeholder handler module)"
    )
    handler_option = (
        f" --handlers {handler_display}" if handler_path is not None else ""
    )
    text = f"""# {project_name}

This directory is generated by Elisa IDE from `{manifest_name}`. The project
document and handwritten Elisa source remain the source of truth; generated
files can be recreated at any time and must not be edited by hand.

## Recreate, build, and run

Run these commands from the project root. Replace `<path-to-elisa-ide>` with
the checkout that contains the Elisa IDE scripts, compiler, and `framework/`.

```sh
python3 <path-to-elisa-ide>/scripts/generate_project.py \
  {manifest_name} \
  --cli <path-to-elisa-ide>/build/elisa_ide_cli \
  --framework-root <path-to-elisa-ide>/framework{handler_option}
<path-to-elisa-ide>/scripts/build_project.sh {manifest_name}{handler_option} \
  --name {namespace}_app
<path-to-elisa-ide>/scripts/run_project.sh {manifest_name}{handler_option} \
  --name {namespace}_app
```

The generator writes this `{output_name}/` directory, including the entry
application `{app_name}`, view modules, exact-hash source-map sidecars, and
`.elisa-ide-generation.json`. `build_project.sh` compiles the entry source
with the resolved Elisa compiler; `run_project.sh` launches that compiled
artifact with the same project inputs.

## File ownership

The ownership manifest is the write boundary for regeneration. Elisa IDE owns
the generated `*.elisa` view/application files, their `*.map.json` source
maps, this README, and any generated handler placeholder. It replaces those
files only when their previous content still matches the recorded hash, and
it removes obsolete files only when they were previously listed as owned.
Handwritten files are outside that manifest and are preserved byte-for-byte.

The current handler source is `{handler_display}`. Put application behavior in
that user-owned module and connect it from the form's Events panel. If a form
has no event connections, the placeholder handler is safe to replace with a
real module before adding the first connection.

## Source navigation

Each generated view has a matching `.map.json` file. The map is bound to the
exact generated-byte hash and records form, node, property, and event spans.
Use it to navigate compiler diagnostics back to the design document or the
handwritten handler. A changed generated file makes its old map stale and is
reported as a regeneration conflict instead of being silently overwritten.
"""
    return text.encode("utf-8")


def load_previous_manifest(output_root: pathlib.Path) -> dict | None:
    path = output_root / ".elisa-ide-generation.json"
    if not path.exists():
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read generation manifest {path}: {exc}") from exc
    if value.get("format") != FORMAT or value.get("version") != VERSION:
        raise ValueError("existing generation manifest is unsupported")
    if not isinstance(value.get("files"), list):
        raise ValueError("existing generation manifest has no file list")
    return value


def current_owned_bytes(output_root: pathlib.Path, manifest: dict) -> dict[str, bytes | None]:
    result: dict[str, bytes | None] = {}
    for item in manifest.get("files", []):
        if not isinstance(item, dict) or not isinstance(item.get("path"), str):
            raise ValueError("existing generation manifest contains an invalid file entry")
        relative = pathlib.PurePosixPath(item["path"])
        if relative.is_absolute() or ".." in relative.parts:
            raise ValueError("existing generation manifest contains an unsafe path")
        path = output_root / pathlib.Path(*relative.parts)
        result[item["path"]] = path.read_bytes() if path.exists() else None
    return result


def validate_transition(output_root: pathlib.Path, previous: dict | None, next_files: dict[str, bytes]) -> None:
    if previous is None:
        for relative in next_files:
            path = output_root / pathlib.Path(*pathlib.PurePosixPath(relative).parts)
            if path.exists():
                raise ValueError(f"unowned output collision: {path}")
        return
    old_files = {item["path"]: item["contentHash"] for item in previous.get("files", [])}
    current = current_owned_bytes(output_root, previous)
    for relative, expected in old_files.items():
        observed = current.get(relative)
        if observed is not None and digest(observed) != expected:
            raise ValueError(f"generated file was modified outside the IDE: {output_root / pathlib.Path(*pathlib.PurePosixPath(relative).parts)}")
    for relative in next_files:
        path = output_root / pathlib.Path(*pathlib.PurePosixPath(relative).parts)
        if path.exists() and relative not in old_files:
            raise ValueError(f"unowned output collision: {path}")


def publish(output_root: pathlib.Path, files: dict[str, bytes], manifest: dict, previous: dict | None) -> None:
    output_root.mkdir(parents=True, exist_ok=True)
    temp = pathlib.Path(tempfile.mkdtemp(prefix=".elisa-ide-stage-", dir=str(output_root.parent)))
    try:
        staged_root = temp / output_root.name
        staged_root.mkdir()
        for relative, content in files.items():
            destination = staged_root / pathlib.Path(*pathlib.PurePosixPath(relative).parts)
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(content)
        manifest_path = staged_root / ".elisa-ide-generation.json"
        manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n", encoding="utf-8")
        # All conflict checks are complete. Replace owned files one by one;
        # source files outside this manifest are never touched.
        for relative in files:
            source = staged_root / pathlib.Path(*pathlib.PurePosixPath(relative).parts)
            destination = output_root / pathlib.Path(*pathlib.PurePosixPath(relative).parts)
            destination.parent.mkdir(parents=True, exist_ok=True)
            os.replace(source, destination)
        next_paths = set(files)
        if previous is not None:
            for item in previous.get("files", []):
                relative = item["path"]
                if relative in next_paths:
                    continue
                obsolete = output_root / pathlib.Path(*pathlib.PurePosixPath(relative).parts)
                if obsolete.exists():
                    obsolete.unlink()
        os.replace(manifest_path, output_root / ".elisa-ide-generation.json")
    finally:
        shutil.rmtree(temp, ignore_errors=True)


def generate(args: argparse.Namespace) -> int:
    project_path = pathlib.Path(args.project).resolve()
    project = read_json(project_path)
    cli = pathlib.Path(args.cli).resolve()
    if not cli.is_file():
        raise ValueError(f"missing Elisa IDE CLI: {cli}")
    run_cli_validate(cli, project_path)

    project_root = project_path.parent
    generation = project.get("generation") or {}
    output_relative = args.output or generation.get("outputRoot", "generated")
    output_root = pathlib.Path(output_relative)
    if not output_root.is_absolute():
        output_root = project_root / output_root
    output_root = output_root.resolve()
    namespace = str(generation.get("namespace") or project.get("name") or "ElisaApp")
    namespace_symbol = re.sub(r"[^A-Za-z0-9_]", "_", namespace)
    if not namespace_symbol or not re.match(r"^[A-Za-z_]", namespace_symbol):
        namespace_symbol = "ElisaApp"

    forms = project.get("forms")
    entry_id = project.get("entryForm")
    if not isinstance(forms, list) or not isinstance(entry_id, str):
        raise ValueError("project must contain forms and entryForm")
    entry = next((item for item in forms if isinstance(item, dict) and item.get("id") == entry_id), None)
    if entry is None or not isinstance(entry.get("path"), str):
        raise ValueError(f"entry form {entry_id!r} is missing")

    form_outputs: list[tuple[str, str, bytes, bytes]] = []
    output_root.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="elisa-ide-forms-", dir=str(output_root.parent)) as temp_name:
        temp_root = pathlib.Path(temp_name)
        for item in forms:
            if not isinstance(item, dict) or not isinstance(item.get("id"), str) or not isinstance(item.get("path"), str):
                raise ValueError("project contains an invalid form entry")
            form_path = (project_root / item["path"]).resolve()
            if project_root not in form_path.parents and form_path != project_root:
                raise ValueError(f"form {item['id']!r} escapes the project directory")
            temp_view = temp_root / (item["id"] + ".elisa")
            temp_map = temp_root / (item["id"] + ".map.json")
            source, source_map = run_cli_generate(cli, form_path, temp_view, temp_map)
            module = module_name(source)
            is_entry = item["id"] == entry_id
            filename = f"{namespace_symbol}_view.elisa" if is_entry else f"{namespace_symbol}_{module}_view.elisa"
            if any(existing[0] == filename or existing[1] == module for existing in form_outputs):
                raise ValueError(f"generated form module or output name is duplicated: {module}")
            form_outputs.append((filename, module, source, source_map))
    # Resolve the entry by stable project form ID rather than by module name.
    entry_index = next(index for index, item in enumerate(forms) if isinstance(item, dict) and item.get("id") == entry_id)
    view_name, module, _, _ = form_outputs[entry_index]
    app_name = f"{namespace_symbol}_app.elisa"
    files: dict[str, bytes] = {}
    for filename, _, source, source_map in form_outputs:
        files[filename] = source
        files[filename + ".map.json"] = source_map

    handler_arg = pathlib.Path(args.handlers).resolve() if args.handlers else (project_root / "src" / "main_handlers.elisa").resolve()
    has_events = any(
        isinstance(item, dict)
        and any(isinstance(event, dict) and isinstance(event.get("handler"), str)
                for event in (item.get("events") or {}).values())
        for form_item in forms if isinstance(form_item, dict)
        for item in (json.loads((project_root / form_item["path"]).resolve().read_text(encoding="utf-8")).get("nodes") or [])
    )
    if not handler_arg.is_file() and has_events:
        raise ValueError(f"user handler source is required for event connections; create or pass --handlers: {handler_arg}")
    framework_include = args.framework_include
    if framework_include is None:
        framework_root = pathlib.Path(args.framework_root).resolve() if args.framework_root else (project_root.parent.parent / "framework").resolve()
        framework_include = os.path.relpath(framework_root / "src/platform/sdl3/ui_sdl3_flat.elisa", output_root).replace(os.sep, "/")
    handlers_include = os.path.relpath(handler_arg, output_root).replace(os.sep, "/") if handler_arg.is_file() else None
    if handlers_include is None:
        # Elisa's stage1 parser requires a declaration-bearing include between
        # the framework/view includes and the application callbacks. A fresh
        # project has no user handlers yet, so publish a tiny generated shim;
        # the first real event connection will require the user-owned module.
        shim_name = f"{namespace_symbol}_handlers.elisa"
        files[shim_name] = (
            "# Generated placeholder; replace with user-owned handlers before adding events.\n"
            "global mutable placeholder_handler_count: i64 = 0\n\n"
            "module PlaceholderHandlers:\n"
            "    public:\n"
            "        def placeholder(widget: usize, event: i32) -> void:\n"
            "            pass\n"
        ).encode("utf-8")
        handlers_include = shim_name
    app_bytes = app_source(framework_include, view_name, handlers_include, module,
                           str(project.get("name") or namespace), int(args.width), int(args.height), int(args.max_frames))
    files[app_name] = app_bytes
    files["README.md"] = project_readme(
        project,
        project_path,
        namespace_symbol,
        app_name,
        handler_arg if handler_arg.is_file() else None,
        output_root,
    )
    next_manifest = {
        "format": FORMAT,
        "version": VERSION,
        "targetId": "sdl3",
        "frameworkId": "elisa-ui",
        "documentHash": digest(project_path.read_bytes()),
        "files": [{"path": key, "contentHash": digest(files[key])} for key in sorted(files)],
    }
    previous = load_previous_manifest(output_root)
    validate_transition(output_root, previous, files)
    publish(output_root, files, next_manifest, previous)
    print(f"generated project: {project_path} -> {output_root}")
    for relative in sorted(files):
        print(f"  {relative}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project")
    parser.add_argument("--output", help="generated output directory, relative to the project")
    parser.add_argument("--handlers", help="user-owned Elisa handler source")
    parser.add_argument("--cli", default="build/elisa_ide_cli")
    parser.add_argument("--framework-root")
    parser.add_argument("--framework-include")
    parser.add_argument("--width", type=int, default=800)
    parser.add_argument("--height", type=int, default=600)
    parser.add_argument("--max-frames", type=int, default=1)
    args = parser.parse_args()
    try:
        return generate(args)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
